/**
 * Regenerate the per-route Open Graph images.
 *
 *   bun run og            # then open the URL it prints (any browser); it writes and exits
 *
 * Why a browser: the cards are typeset in the site's own fonts, and rasterising text in Node
 * would mean a headless renderer and a font pipeline. The page draws each card on a canvas and
 * POSTs the PNG back here, so the only new moving part is this script.
 *
 * The QR matrices come from the engine, not from the page, so the images cannot drift from
 * what the generator would produce for the same URL.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { encode } from '../../packages/engine/src/encode.ts';
import { OG_ROUTES } from './routes.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../..');
const outDir = resolve(root, 'apps/site/static/og');
const manifest = resolve(root, 'apps/site/src/lib/og-images.ts');
const fontDir = resolve(root, 'apps/site/node_modules/@fontsource-variable');
const SITE = 'https://stoneqr.app';
const PORT = 5199;

const FONTS = {
	'display.woff2': `${fontDir}/fraunces/files/fraunces-latin-full-normal.woff2`,
	'sans.woff2': `${fontDir}/instrument-sans/files/instrument-sans-latin-wght-normal.woff2`,
	'mono.woff2': `${fontDir}/jetbrains-mono/files/jetbrains-mono-latin-wght-normal.woff2`
};

const cards = OG_ROUTES.map((route) => {
	const qr = encode(`${SITE}${route.path}`, { ecc: 'M' });
	return { ...route, matrix: qr.matrix, size: qr.size };
});

mkdirSync(outDir, { recursive: true });
const written = new Set();
let finish;
const done = new Promise((r) => (finish = r));

const file = (path, type) => new Response(readFileSync(path), { headers: { 'content-type': type } });

const server = Bun.serve({
	port: PORT,
	async fetch(request) {
		const url = new URL(request.url);
		if (url.pathname === '/') return file(resolve(here, 'page.html'), 'text/html; charset=utf-8');
		if (url.pathname === '/card.js') return file(resolve(here, 'card.js'), 'text/javascript');
		if (url.pathname === '/cards.json') return Response.json(cards);
		if (FONTS[url.pathname.slice(1)]) return file(FONTS[url.pathname.slice(1)], 'font/woff2');

		if (request.method === 'POST' && url.pathname.startsWith('/save/')) {
			const slug = url.pathname.slice('/save/'.length);
			if (!OG_ROUTES.some((r) => r.slug === slug)) return new Response('unknown route', { status: 400 });
			const bytes = new Uint8Array(await request.arrayBuffer());
			writeFileSync(resolve(outDir, `${slug}.png`), bytes);
			written.add(slug);
			console.log(`  ${String(bytes.length).padStart(7)} bytes  og/${slug}.png`);
			if (written.size === OG_ROUTES.length) finish();
			return new Response('ok');
		}
		return new Response('not found', { status: 404 });
	}
});

console.log(`Open http://localhost:${PORT}/ to draw ${cards.length} cards into apps/site/static/og/`);
await done;
server.stop(true);

// The site reads this list to pick a card; anything not in it falls back to /og.png.
writeFileSync(
	manifest,
	`// Generated by scripts/og/generate.mjs. Run \`bun run og\` after adding a route; do not edit.\n` +
		`export const OG_IMAGES: ReadonlySet<string> = new Set([\n` +
		OG_ROUTES.map((r) => `\t'${r.slug}'`).join(',\n') +
		`\n]);\n`
);
console.log(`\nWrote ${written.size} images and the manifest.`);
