/**
 * Regenerate the per-route Open Graph images.
 *
 *   bun run og            # then open the URL it prints (any browser); it writes and exits
 *   bun run og --headless # the same, driven in headless Chrome
 *
 * Why a browser: the cards are typeset in the site's own fonts, and rasterising text in Node
 * would mean a headless renderer and a font pipeline. The page draws each card on a canvas and
 * POSTs the PNG back here, so the only new moving part is this script.
 *
 * The QR matrices come from the engine, not from the page, so the images cannot drift from
 * what the generator would produce for the same URL.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { encode } from '../../packages/engine/src/encode.ts';
import { HOME_CARD, OG_ROUTES } from './routes.mjs';
import { awaitPage } from '../headless.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../..');
const outDir = resolve(root, 'apps/site/static/og');
const manifest = resolve(root, 'apps/site/src/lib/og-images.ts');
const fontDir = resolve(root, 'apps/site/node_modules/@fontsource-variable');
const SITE = 'https://stoneqr.app';
const PORT = 5199;

const FONTS = {
	'archivo.woff2': `${fontDir}/archivo/files/archivo-latin-wdth-normal.woff2`
};

// The home card is drawn too, to apps/site/static/og.png, so the page every share of the site
// opens on carries the same look as the rest.
const cards = [HOME_CARD, ...OG_ROUTES].map((route) => {
	const qr = encode(route.path ? `${SITE}${route.path}` : SITE, { ecc: 'M' });
	return { ...route, matrix: qr.matrix, size: qr.size };
});

mkdirSync(outDir, { recursive: true });
const written = new Set();
let finish;
const done = new Promise((r) => (finish = r));

const file = (path, type) => new Response(readFileSync(path), { headers: { 'content-type': type } });

const server = Bun.serve({
	port: PORT,
	async fetch(request) {
		const url = new URL(request.url);
		if (url.pathname === '/') return file(resolve(here, 'page.html'), 'text/html; charset=utf-8');
		if (url.pathname === '/card.js') return file(resolve(here, 'card.js'), 'text/javascript');
		if (url.pathname === '/cards.json') return Response.json(cards);
		if (FONTS[url.pathname.slice(1)]) return file(FONTS[url.pathname.slice(1)], 'font/woff2');

		if (request.method === 'POST' && url.pathname.startsWith('/save/')) {
			const slug = url.pathname.slice('/save/'.length);
			const home = slug === 'home';
			if (!home && !OG_ROUTES.some((r) => r.slug === slug)) return new Response('unknown route', { status: 400 });
			const bytes = new Uint8Array(await request.arrayBuffer());
			const target = home ? resolve(outDir, '../og.png') : resolve(outDir, `${slug}.png`);
			writeFileSync(target, bytes);
			written.add(slug);
			console.log(`  ${String(bytes.length).padStart(7)} bytes  ${home ? 'og.png' : `og/${slug}.png`}`);
			if (written.size === cards.length) finish();
			return new Response('ok');
		}
		return new Response('not found', { status: 404 });
	}
});

await awaitPage(`http://localhost:${PORT}/`, done, { prompt: `to draw ${cards.length} cards into apps/site/static/og/`, timeoutMs: 120_000 });
server.stop(true);

// The site reads this list to pick a card; anything not in it falls back to /og.png.
writeFileSync(
	manifest,
	`// Generated by scripts/og/generate.mjs. Run \`bun run og\` after adding a route; do not edit.\n` +
		`export const OG_IMAGES: ReadonlySet<string> = new Set([\n` +
		OG_ROUTES.map((r) => `\t'${r.slug}'`).join(',\n') +
		`\n]);\n`
);
console.log(`\nWrote ${written.size} images (og.png and og/*) and the manifest.`);
