// Generated by scripts/fonts.mjs (bun run fonts). Do not edit.
/** First-paint font files, preloaded by the layout so they load alongside the stylesheet. */
export const FONT_PRELOADS = [
	"/fonts/fraunces.7716ddd0.woff2",
	"/fonts/instrument-sans.13f38f0b.woff2",
	"/fonts/jetbrains-mono.b5d6e25a.woff2"
] as const;
