// Generated by scripts/og/generate.mjs. Run `bun run og` after adding a route; do not edit.
export const OG_IMAGES: ReadonlySet<string> = new Set([
	'never-expires',
	'wifi',
	'vcard',
	'event',
	'logo',
	'photo',
	'bulk',
	'print-size',
	'compare',
	'open-source',
	'privacy'
]);
