/**
 * Build the first-paint font files.
 *
 *   bun run fonts
 *
 * The site's three families ship from @fontsource-variable as full variable fonts (about 140 KB
 * for the Latin files), and the browser cannot start fetching them until the stylesheet has
 * arrived and been parsed. This script cuts each family down to what the first paint needs:
 * the basic Latin repertoire (ASCII, Latin-1, the common typographic punctuation) and only the
 * axis ranges the stylesheet uses. The fontsource faces stay imported in app.css as the fallback
 * for any other character, so a Polish surname in a vCard still renders in the right family; the
 * browser downloads that fuller file only when such a character appears.
 *
 * Outputs (all regenerated; do not edit by hand):
 *   apps/site/static/fonts/<family>.<hash>.woff2   content-hashed, cached immutable by _headers
 *   apps/site/src/lib/fonts.css                     the @font-face rules (imported after fontsource)
 *   apps/site/src/lib/fonts.ts                      the hrefs the layout preloads
 *   apps/site/static/_headers                       a Link: preload header per page, between markers;
 *                                                   Cloudflare sends it as a 103 Early Hint, so the
 *                                                   fonts start before the HTML has arrived
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import subsetFont from '../apps/site/node_modules/subset-font/index.js';
import { OG_ROUTES } from './og/routes.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = resolve(root, 'apps/site/node_modules/@fontsource-variable');
const outDir = resolve(root, 'apps/site/static/fonts');

/** Basic Latin: ASCII, Latin-1 Supplement, and the punctuation the site copy uses. */
const RANGES = [
	[0x20, 0x7e],
	[0xa0, 0xff],
	[0x2013, 0x2014], // en and em dash
	[0x2018, 0x2019], // single quotes
	[0x201c, 0x201d], // double quotes
	[0x2022, 0x2022], // bullet
	[0x2026, 0x2026], // ellipsis
	[0x20ac, 0x20ac], // euro
	[0x2122, 0x2122], // trade mark
	[0x2212, 0x2212] // minus
];
const text = RANGES.flatMap(([a, b]) => Array.from({ length: b - a + 1 }, (_, i) => String.fromCodePoint(a + i))).join('');
const unicodeRange = RANGES.map(([a, b]) => (a === b ? `U+${a.toString(16)}` : `U+${a.toString(16)}-${b.toString(16)}`)).join(', ');

/**
 * One entry per family. `axes` pins what the stylesheet never varies and narrows what it does;
 * `weight` is the font-weight descriptor the narrowed face advertises.
 */
const FAMILIES = [
	{
		name: 'fraunces',
		family: 'Fraunces Variable',
		file: 'fraunces/files/fraunces-latin-opsz-normal.woff2',
		// h1 to h3 and .display are the only display text, at weight 500 and opsz 18, 36, or 72;
		// pinning the weight halves the file. The fontsource file carries only
		// the wght and opsz axes, so the SOFT and WONK settings in app.css have never had an effect.
		axes: { wght: 500, opsz: { min: 18, max: 72 } },
		weight: '500'
	},
	{
		name: 'instrument-sans',
		family: 'Instrument Sans Variable',
		file: 'instrument-sans/files/instrument-sans-latin-wght-normal.woff2',
		axes: {},
		weight: '400 700'
	},
	{
		name: 'jetbrains-mono',
		family: 'JetBrains Mono Variable',
		file: 'jetbrains-mono/files/jetbrains-mono-latin-wght-normal.woff2',
		// Labels, tickets, and numeric inputs at 400 and 500 only.
		axes: { wght: { min: 400, max: 500 } },
		weight: '400 500'
	}
];

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const faces = [];
const hrefs = [];
for (const f of FAMILIES) {
	const input = readFileSync(resolve(src, f.file));
	const out = await subsetFont(input, text, { targetFormat: 'woff2', variationAxes: f.axes });
	const hash = createHash('sha256').update(out).digest('hex').slice(0, 8);
	const name = `${f.name}.${hash}.woff2`;
	writeFileSync(resolve(outDir, name), out);
	hrefs.push(`/fonts/${name}`);
	faces.push(
		`@font-face {\n\tfont-family: '${f.family}';\n\tfont-style: normal;\n\tfont-weight: ${f.weight};\n\tfont-display: swap;\n\tsrc: url('/fonts/${name}') format('woff2-variations');\n\tunicode-range: ${unicodeRange};\n}`
	);
	console.log(`${name}\t${input.length} -> ${out.length} B`);
}

const banner = '/* Generated by scripts/fonts.mjs (bun run fonts). Do not edit. */\n';
writeFileSync(
	resolve(root, 'apps/site/src/lib/fonts.css'),
	banner +
		'/* Declared after the @fontsource-variable imports, so these faces win for the basic Latin range\n   and the fuller fontsource files are fetched only for characters outside it. */\n' +
		faces.join('\n') +
		'\n'
);
writeFileSync(
	resolve(root, 'apps/site/src/lib/fonts.ts'),
	'// Generated by scripts/fonts.mjs (bun run fonts). Do not edit.\n/** First-paint font files, preloaded by the layout so they load alongside the stylesheet. */\nexport const FONT_PRELOADS = ' +
		JSON.stringify(hrefs, null, '\t') +
		' as const;\n'
);

// Early Hints: one Link header per page (not /*, which would stamp it on every image too).
const headersPath = resolve(root, 'apps/site/static/_headers');
const BEGIN = '# BEGIN fonts (generated by scripts/fonts.mjs)';
const END = '# END fonts';
const link = hrefs.map((h) => `<${h}>; rel=preload; as=font; crossorigin`).join(', ');
const block = ['/', ...OG_ROUTES.map((r) => r.path)].map((path) => `${path}\n  Link: ${link}`).join('\n');
const headers = readFileSync(headersPath, 'utf8');
const start = headers.indexOf(BEGIN);
const end = headers.indexOf(END);
const generated = `${BEGIN}\n${block}\n${END}`;
const next = start === -1 ? `${headers.trimEnd()}\n\n${generated}\n` : headers.slice(0, start) + generated + headers.slice(end + END.length);
writeFileSync(headersPath, next);
console.log(readdirSync(outDir).join(' '));
